version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9002:9000" # API
      - "9003:9001" # Console Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:
