version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
      MYSQL_USER: crmuser
      MYSQL_PASSWORD: crmpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - crm-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm-api
    restart: always
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=crm;User=crmuser;Password=crmpass;
    depends_on:
      - mysql
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge

volumes:
  db_data:
